blank_issues_enabled: false
contact_links:
  - name: Translations
    about: We'd like to organise translations on Launchpad Rosetta — but if
      that's too much effort for you, attaching a .po file to an issue or
      merge request is just as welcome.
    url: https://translations.launchpad.net/scantpaper
