name: Build packages
on: [push]

permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Define variables
        run: |
          (
            VERSION=$(echo "${GITHUB_REF_NAME}" | sed -e 's/^v//')
            if ! [[ $VERSION =~ ^[0-9] ]]; then
              VERSION="$(sed -n "s/^[[:space:]]*VERSION[[:space:]]*=[[:space:]]*['\"]\([^'\"]*\)['\"].*/\1/p" REPO/scantpaper/const.py || true)+${{github.sha}}"
            fi
            echo "GITHUB_REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2)"
            echo "VERSION=${VERSION}"
            echo "DEB_ARCHITECTURE=${ARCHITECTURE:-all}"
            echo "RPM_ARCHITECTURE=${ARCHITECTURE:-noarch}"
            echo "RELEASE=1"
            echo "AUTHOR=Jeffrey Ratcliffe <jffry@posteo.net>"
            cd REPO
            echo "FIRST_YEAR=$(git log $(git rev-list --max-parents=0 HEAD) --date="format:%Y" --format="format:%ad")"
            echo "THIS_COMMIT_YEAR=$(git log HEAD -n1 --date="format:%Y" --format="format:%ad")"
            echo "THIS_COMMIT_DATE=$(git log HEAD -n1 --format="format:%as")"
            if [ "$FIRST_YEAR" == "$THIS_COMMIT_YEAR" ]
            then
              echo "YEAR_RANGE=$FIRST_YEAR"
            else
              echo "YEAR_RANGE=${FIRST_YEAR}-${THIS_COMMIT_YEAR}"
            fi
            cd ..
          ) >> $GITHUB_ENV

      - name: Create control files
        # Fields from https://www.debian.org/doc/debian-policy/ch-controlfields.html#binary-package-control-files-debian-control
        run: |
          mkdir -p REPO/debian/upstream
          mkdir -p REPO/debian/source
          echo "3.0 (quilt)" | tee REPO/debian/source/format
          (
            echo "Source: ${GITHUB_REPO_NAME}"
            echo "Section: utils"
            echo "Testsuite: autopkgtest-pkg-python"
            echo "Build-Depends: debhelper-compat (= 13),"
            echo "               dh-python,"
            echo "               python3-all,"
            echo "               python3-pip,"
            echo "               python3-setuptools,"
            echo "               python3-wheel"
            echo "Build-Depends-Indep: fonts-noto-extra,"
            echo "                     gettext,"
            echo "                     ghostscript,"
            echo "                     gir1.2-gtk-3.0,"
            echo "                     gir1.2-goocanvas-2.0,"
            echo "                     gsfonts,"
            echo "                     imagemagick,"
            echo "                     librsvg2-common,"
            echo "                     libtiff-tools,"
            echo "                     ocrmypdf,"
            echo "                     poppler-utils,"
            echo "                     python3-gi,"
            echo "                     python3-gi-cairo,"
            echo "                     python3-iso639,"
            echo "                     python3-sane,"
            echo "                     python3-tesserocr,"
            echo "                     python3-polib,"
            echo "                     python3-pytest-cov,"
            echo "                     python3-pytest-timeout,"
            echo "                     python3-pytest-pylint,"
            echo "                     python3-pytest-mock,"
            echo "                     python3-pytest-xvfb,"
            echo "                     sane-utils (>= 1.0.17),"
            echo "                     xauth,"
            echo "                     xfonts-base"
            echo "Maintainer: ${AUTHOR}"
            echo "Standards-Version: 4.7.3"
            echo "Vcs-Git: https://github.com/carygravel/scantpaper.git"
            echo "Vcs-Browser: https://github.com/carygravel/scantpaper"
            echo "Homepage: https://github.com/carygravel/scantpaper"
            echo ""
            echo "Package: ${GITHUB_REPO_NAME}"
            echo "Architecture: ${DEB_ARCHITECTURE}"
            echo "Depends: gir1.2-gtk-3.0,"
            echo "         gir1.2-goocanvas-2.0,"
            echo "         imagemagick,"
            echo "         librsvg2-common,"
            echo "         libtiff-tools,"
            echo "         ocrmypdf,"
            echo "         python3-gi,"
            echo "         python3-gi-cairo,"
            echo "         python3-iso639,"
            echo "         python3-sane,"
            echo "         python3-tesserocr,"
            echo "         sane-utils (>= 1.0.17),"
            echo "         \${misc:Depends},"
            echo "         \${python3:Depends}"
            echo "Recommends: djvulibre-bin,"
            echo "            pdftk,"
            echo "            tesseract-ocr,"
            echo "            unpaper,"
            echo "            xdg-utils"
            echo "Description: GUI to produce PDFs or DjVus from scanned documents"
            echo " Only five clicks are required to scan several pages and then save all or"
            echo " a selection as a PDF or DjVu file, including metadata if required."
            echo " ."
            echo " scantpaper can control flatbed or sheet-fed (ADF) scanners with SANE,"
            echo " and can scan multiple pages at once. It presents a thumbnail view of"
            echo " scanned pages, and permits simple operations such as cropping, rotating"
            echo " and deleting pages."
            echo " ."
            echo " OCR can be used to recognise text in the scans, and the output"
            echo " embedded in the PDF or DjVu."
            echo " ."
            echo " The resulting document may be saved as a PDF, DjVu, multipage TIFF file, or"
            echo " single page image file."
            echo " ."
            echo " PDF conversion is done by ocrmypdf."
            if [ -n "${HOMEPAGE}" ]
            then
              echo "Homepage: ${HOMEPAGE}"
            fi
          ) | tee REPO/debian/control
          (
            echo "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/"
            echo "Upstream-Name: scantpaper"
            echo "Upstream-Contact: Jeffrey Ratcliffe <jffry@posteo.net>"
            echo "Source: https://github.com/carygravel/scantpaper"
            echo ""
            echo "Files: *"
            echo "Copyright: 2006--2026 Jeffrey Ratcliffe"
            echo "License: GPL-3"
            echo " The full text of the GPL is available on Debian systems in"
            echo " /usr/share/common-licenses/GPL-3"
            echo ""
            echo "Files: scantpaper.appdata.xml"
            echo "Copyright: 2006--2026 Jeffrey Ratcliffe"
            echo "License: CC0-1.0"
            echo " The full text of the CC0-1.0 licence is available on Debian systems in"
            echo " /usr/share/common-licenses/CC0-1.0"
            echo ""
            echo "Files: icons/hicolor/scalable/apps/scanner.svg"
            echo "Copyright: 2007 Frédéric Bellaiche"
            echo "License: GPL"
            echo " The full text of the GPL is available on Debian systems in"
            echo " /usr/share/common-licenses/GPL"
            echo ""
            echo "Files: icons/hicolor/scalable/apps/pdf.svg"
            echo "Copyright: 2004 David Vignoni"
            echo "License: LGPL-2.1"
            echo " The full text of the GPL is available on Debian systems in"
            echo " /usr/share/common-licenses/LGPL-2.1"
          ) | tee REPO/debian/copyright
          (
            echo "${GITHUB_REPO_NAME} (${VERSION}-0) unstable; urgency=medium"
            echo ""
            echo "  * New upstream release candidate"
            echo ""
            echo " -- ${AUTHOR}  $(date --rfc-email)"
            echo ""
          ) | tee REPO/debian/changelog
          (
            echo "#!/usr/bin/make -f"
            echo "# Uncomment this to turn on verbose mode."
            echo "export DH_VERBOSE=1"
            echo ""
            echo "# Prevent pip from using the cache directory, which can cause issues in some"
            echo "# CI environments and is not needed for building the package."
            echo "export PIP_NO_CACHE_DIR=1"
            echo "export XDG_CACHE_HOME=$(CURDIR)/.cache"
            echo ""
            echo "%:"
            echo "	dh \$@ --with python3 --buildsystem=pybuild"
            echo ""
            echo "override_dh_auto_install:"
            echo "	python3 -m pip install --no-deps --no-build-isolation --root=\$(CURDIR)/debian/scantpaper --prefix=/usr ."
            echo "	# dh_auto_install will still place any additional files; ensure dh runs"
            echo "	dh_auto_install --destdir=\$(CURDIR)/debian/scantpaper || true"
            echo "	rm -rf \$(CURDIR)/debian/scantpaper/usr/local || true # FIXME: there has to be a better way to prevent pip from installing to /usr/local"
            echo "	# install locale files"
            echo "	# can't directly install to /usr/share/locale since pybuild seems to delete them"
            echo "	python3 \$(CURDIR)/dev/compile_mo.py --src \$(CURDIR)/po --out \$(CURDIR)/locale --domain scantpaper || true"
            echo "	mkdir -p \$(CURDIR)/debian/scantpaper/usr/share"
            echo "	cp -a \$(CURDIR)/locale \$(CURDIR)/debian/scantpaper/usr/share/"
            echo ""
            echo "# https://people.debian.org/~eriberto/README.package-tests.html"
            echo "override_dh_auto_test: ;"
          ) | tee REPO/debian/rules
          (
            echo "icons/* usr/share/icons/"
            echo "org.scantpaper.desktop usr/share/applications"
            echo "scantpaper.appdata.xml usr/share/metainfo"
          ) | tee REPO/debian/install
          (
            echo "Bug-Database: https://github.com/carygravel/scantpaper/issues"
            echo "Bug-Submit: https://github.com/carygravel/scantpaper/issues/new"
            echo "Changelog: https://github.com/carygravel/scantpaper/blob/main/changelog.md"
            echo "Repository-Browse: https://github.com/carygravel/scantpaper"
            echo "Repository: https://github.com/carygravel/scantpaper"
          ) | tee REPO/debian/upstream/metadata
          (
            echo "Version: 5"
            echo ""
            echo "Template: Github"
            echo "Owner: carygravel"
            echo "Project: @PACKAGE@"
          ) | tee REPO/debian/watch

#      - name: Create Spec File
#        run: PATH="REPO/.github/scripts:${PATH}" create_spec_file.sh

      - name: Install dependencies
        run: |
            sudo add-apt-repository ppa:jeffreyratcliffe/ppa
            sudo apt-get update
            sudo apt-get install -y build-essential debhelper devscripts fakeroot lintian equivs
            sudo mk-build-deps --install --remove REPO/debian/control # Install build dependencies from debian/control

      - name: Build DEB Package
        run: cd REPO && debuild -i -us -uc -b && dpkg-deb --contents ../${{ env.GITHUB_REPO_NAME }}_${{ env.VERSION }}-0_all.deb

#      - name: Build RPM Package
#        run: sudo rpmbuild --define "_topdir $(pwd)" -bb SPECS/${GITHUB_REPO_NAME}.spec

      - name: Upload packages
        run: ls -l
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GITHUB_REPO_NAME }}_${{ env.VERSION }}-0_all.deb
          path: ${{ env.GITHUB_REPO_NAME }}_${{ env.VERSION }}-0_*

      - name: Release packages
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.GITHUB_REPO_NAME }}_${{ env.VERSION }}-0_all.deb
